### ISSUE TITLE
Quit button does nothing on html5 build

### ISSUE THREAD

**Issue by plexsoup** [godot-wildlings/gwj8#12]
Not sure if it can do anything. Here's some info about Godot html5 limitations: https://docs.godotengine.org/en/3.1/getting_started/workflow/export/exporting_for_web.html

If it can't quit, we should send the game to a black screen and turn off audio.

**Comment by kvonspiczak** [comment]
i noticed the same behavior on my space jumper game. i guess its a browser limitation since it cannot quit the browser window for you (permission issue)

**Comment by plexsoup** [comment]
solved by pausing the game and showing a credits screen
