### ISSUE TITLE
need a warning for a damaged suit

### ISSUE THREAD

**Issue by plexsoup** [godot-wildlings/gwj8#14]
We have a low oxygen warning at 33%, but we don't have any warning for when the suit integrity is low.

**Comment by plexsoup** [comment]
In case anyone's wondering how the voiceovers are made, I use audacity to record my speakers, then go to https://ttsreader.com/ and choose a UK voice. 
Then I use a time-track in audacity to warp the voice.

**Comment by Borupirax** [comment]
Maybe a screen flash/flickering effect, something like what you would see in modern FPS games with the four corners of the screen going slightly red in a gradient towards the center of the screen.

**Comment by plexsoup** [comment]
added an audio and visual warning, similar to the low-oxygen warning
