### ISSUE TITLE
it's not obvious to players why they can't fling the asteroids

### ISSUE THREAD

**Issue by plexsoup** [godot-wildlings/gwj8#16]
A new player might think it's a bug.

**Comment by plexsoup** [comment]
maybe add a distorted audio cue when the player tries to click on an asteroid?

**Comment by kvonspiczak** [comment]
maybe we can add a hover effect on draggable objects?

**Comment by plexsoup** [comment]
I added text to the tutorial level about carbon and organic matter.
I also added two asteroids to the tutorial so players will notice that they can't grab them.
