### ISSUE TITLE
forgot to update the quit button on the endscreen

### ISSUE THREAD

**Issue by plexsoup** [godot-wildlings/gwj8#18]
copy the settings/code from the options-menu quit button and apply them to the end-screen.

or maybe write a static quit_game function in global and use that instead of get_tree().quit()

**Comment by Borupirax** [comment]
Wrote the second one. Will update thru Fork.

**Comment by plexsoup** [comment]
moved quit procedure into main.tscn. It needed GUI elements, so it made more sense there than in the game.gd singleton.
