### ISSUE TITLE
We don't tell the player that they can land on planets to get oxygen.

### ISSUE THREAD

**Issue by plexsoup** [godot-wildlings/gwj8#21]
Astute players will figure this out. There's an atmospheric halo around the planets and the character makes a breathing noise when you touch down. But we don't specifically mention it anywhere.
So some players might get frustrated when they asphyxiate.

**Comment by kvonspiczak** [comment]
i like that, i think its fine to keep it this way. we might add a little hint to it, but dont tell them exactly what to do.

**Comment by Borupirax** [comment]
A subtle audio event might also add some level of polish. Something like a person taking in a quick but heavy breath

**Comment by plexsoup** [comment]
We already had a breathing noise on planets, but I guess it was too subtle. I've increased the volume so it's more obvious.
